GET http://localhost:3000/students

### 

POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Mariam",
  "age": 21,
  "email": "mari@example.com",
  "classes": [1]
}

###

DELETE http://localhost:3000/students/905d

###

PUT http://localhost:3000/students/4
Content-Type: application/json

{
  "id": 4,
  "name": "Eric",
  "age": 22,
  "email": "eric@example.comm",
  "classes": [1]
}

###

POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Test user",
  "age": 20,
  "email": "t@test.com",
  "classes": [1]
}

